name: minaslar
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter
  mask_text_input_formatter: ^2.4.0  # Adicione esta linha
  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter  # Corrigido (estava flutte)

  # Adicionei a versão aqui
  flutter_launcher_icons: ^0.13.1 
  
  flutter_lints: ^6.0.0

# =================================================
# CONFIGURAÇÃO DOS ÍCONES (Fica fora das dependências)
# =================================================
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 

flutter:
  uses-material-design: true

  assets:
    - assets/