name: minaslar
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  
  # --- Dependências do Projeto ---
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  supabase_flutter: ^2.8.0
  mask_text_input_formatter: ^2.4.0
  cupertino_icons: ^1.0.8
  intl: ^0.18.0 # Deixei apenas uma vez. A 0.18.0 funciona bem com o table_calendar
  fl_chart: ^0.66.2
  url_launcher: ^6.3.2
  geolocator: ^13.0.0  # Para pegar a posição atual
  geocoding: ^3.0.0    # Para transformar endereço em coordenadas
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Ferramentas de desenvolvimento
  flutter_launcher_icons: ^0.13.1 
  flutter_lints: ^2.0.0 # Atenção: lints 6.0.0 pode pedir SDK mais novo. Se der erro, use 2.0 ou 3.0

# =================================================
# CONFIGURAÇÃO DOS ÍCONES
# =================================================
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 

flutter:
  uses-material-design: true

  # Configuração de Assets
  assets:
    - assets/